### ISSUE TITLE
Reuse of testcontaines requires additional setup. 

### ISSUE THREAD

**Issue by vrogach2020** [tarantool/cartridge-java-testcontainers#13]
On windows environment you need to add the following .testcontainers.properties file in your home directory to get 'withReuse' option working:
```
testcontainers.reuse.enable=true
```

See https://stackoverflow.com/questions/62425598/how-to-reuse-testcontainers-between-multiple-springboottests

**Comment by andrei-punko** [comment]
It's looks strange - requirement to add some property **on Windows only** to have same behavior on all platforms.
Library should have same behavior for same set of properties on all platforms.

**Comment by akudiyar** [comment]
Related issue: https://github.com/testcontainers/testcontainers-java/pull/1781

**Comment by vrogach2020** [comment]
@andrei-punko you are right. It seems that behavior should be similar for all environments: reuse option is off by default. See 
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L167

I've tested the library on Ubuntu and Windows envs and observe that TC reuse is not working on my Ubuntu 20 with latest docker versions. Looks like 'reuse' is not a stable feature but I think we should add some notes on this property.

**Comment by bsideup** [comment]
`withReuse` says that the container is "reusable" (as in, can be used by multiple test sessions, not just tests in the same testing session)

`testcontainers.reuse.enable=true` is an OS-independent option to say "this **environment** supports the containers reuse"

**Comment by vrogach2020** [comment]
We have nothing to do with our library here after @bsideup 's clarifing comment.
Closing issue
