### ISSUE TITLE
Additional ports mapping

### ISSUE THREAD

**Issue by bitgorbovsky** [tarantool/cartridge-java-testcontainers#65]
There is no possibility to assign additional exposed ports to container. For example, we want to run some specific server.lua script under tarantool container and this script activates metrics module and exposes them at specific port. On test side we want to check metrics by http, but we have only one port for client connection.

So, we need methods for adding other exposed/mapped ports.

**Comment by ArtDu** [comment]
@bitgorbovsky 
We can just open ports by addExposedPorts method before container starting. Like this:
```java
// tarantoolContainer = new TarantoolContainer...
...
tarantoolContainer.addExposedPort(8081);
...
// and we may obtain mapped port after container starting
tarantoolContainer.getMappedPort(8081);
```

But for this we need to remove withExposedPorts here
https://github.com/tarantool/cartridge-java-testcontainers/blob/d6f21a628c155c78e19dcf87b1636536ebc97cf0/src/main/java/org/testcontainers/containers/TarantoolCartridgeContainer.java#L466
https://github.com/tarantool/cartridge-java-testcontainers/blob/d6f21a628c155c78e19dcf87b1636536ebc97cf0/src/main/java/org/testcontainers/containers/TarantoolContainer.java#L352

which overwrite list with exposed ports on starting stage
